.version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4.27-rc0-focal
    restart: always
    ports:
      - "27017:27017"
    command: --wiredTigerCacheSizeGB 1.5
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 25s
      retries: 3
  pg:
    container_name: pg
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 25s
      retries: 3
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./reids:/data

  server:
    container_name: server
    build: ./server
    depends_on:
      pg:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - 4500:4500
    environment:
      # NODE_ENV: production
      CONNECTION_STRING: mongodb://mongodb:27017/project-games
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGNAME: postgres
      PGDATABASE: project-games-users
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: "SECRET"
      EXPRESSPORT: 4500
    links:
      - pg
      - redis
      - mongodb
      - client
    develop:
      watch:
        - action: rebuild
          path: ./server/app/package.json
    volumes:
      - ./server/app/src:/app/src

  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: ./client/vite-project/package.json
    volumes:
      - ./client/vite-project/src:/app/src

volumes:
  redis:
    driver: local
  pg:
    driver: local
  mongodata:
    driver: local
